version: "3"

services:
    web:
        build:
            context: ./app
            dockerfile: Dockerfile
        command: >
            sh -c "pip install -r requirements.txt
                python manage.py migrate
                python manage.py collectstatic --no-input
                python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./app/:/usr/src/app/
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/mediafiles
        expose:
            - "8000"
        ports:
            - 8000:8000
        environment:
            POSTGRES_USER: ${POSTGRES_USER} # The PostgreSQL user (useful to connect to the database)
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # The PostgreSQL password (useful to connect to the database)
            POSTGRES_DB: ${POSTGRES_DB} # The PostgreSQL default database (automatically created at first launch)
        restart: always
        depends_on:
            - db

    db:
        image: postgres:11
        restart: always
        ports:
        - 5432:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER} # The PostgreSQL user (useful to connect to the database)
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # The PostgreSQL password (useful to connect to the database)
            POSTGRES_DB: ${POSTGRES_DB} # The PostgreSQL default database (automatically created at first launch)

    nginx:
        build: ./compose/nginx
        volumes:
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/mediafiles
        ports:
            - "80:80"
        depends_on:
            - web

    webpack:
      image: node:12.13-alpine
      volumes:
        - ./app:/usr/src/app
      working_dir: /usr/src/app
      command: >
        sh -c "npm install
              npm run watch"
      depends_on:
        - web

volumes:
    static_volume:
    media_volume:
