version: "3"

services:
    web:
      build:
          context: ./app
          dockerfile: Dockerfile
      command: >
        sh -c "pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --no-input
            python manage.py runserver 0.0.0.0:8000"
      volumes:
          - ./app/:/usr/src/app/
      expose:
          - "8000"
      ports:
          - 8000:8000
      env_file:
          - ./.env.prod
      restart: always
      depends_on:
          - db

    db:
        image: postgres:11
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=isjuris
            - POSTGRES_PASSWORD=i5juris.0rg
            - POSTGRES_DB=isjurisdb

    nginx:
      build: ./compose/nginx
      volumes:
          - ./app/staticfiles:/django_static
      ports:
        - "80:80"
      depends_on:
          - web

    webpack:
      image: node:12.13-alpine
      volumes:
        - ./app:/usr/src/app
      working_dir: /usr/src/app
      command: >
        sh -c "npm install
              npm run watch"
      depends_on:
        - web

volumes:
    postgres_data:
